parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DEFAULT_DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/orm_data.sqlite'
    env(PHPCR_DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/phpcr_data.sqlite'
    env(WORKFLOW_DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/workflow_data.sqlite'

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_sqlite'
                url: '%env(resolve:DEFAULT_DATABASE_URL)%'
            phpcr:
                driver: 'pdo_sqlite'
                url: '%env(resolve:PHPCR_DATABASE_URL)%'
            workflow:
                driver: 'pdo_sqlite'
                url: '%env(resolve:WORKFLOW_DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App\Entity'
                        alias: App

doctrine_phpcr:
    session:
        default_session: ~
        sessions:
            default:
                backend:
                    type: doctrinedbal
                    connection: phpcr
                    # caches:
                    #     meta: doctrine_cache.providers.phpcr_meta
                    #     nodes: doctrine_cache.providers.phpcr_nodes
                    logging: "%kernel.debug%"
                    profiling: "%kernel.debug%"
                workspace: default
                username: admin
                password: admin
    odm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_document_manager: ~
        document_managers:
            default:
                session: default
                auto_mapping: false
                mappings:
                    App:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App\Document'
                        alias: 'App'
                    JBJ\Workflow:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'JBJ\Workflow\Document'
                        alias: 'Workflow'

